/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.x.scheduling;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Επιλέξτε ένα πρόβλημα");

        jButton1.setText("CAR F-92");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("CAR S-91");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("EAR F-83");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("HEC S-92");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("KFU S-93");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("LSE F-91");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("PUR S-92");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("RYE S-93");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("STA F-83");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("TRE S-92");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("UTA S-92");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setText("UTE S-92");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setText("YOR F-83");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton9)
                            .addComponent(jButton5)
                            .addComponent(jButton12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jButton8)
                            .addComponent(jButton11)
                            .addComponent(jButton13))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(32, 32, 32)
                .addComponent(jButton7)
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
       Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\car-f-92.stu","1","32","0.14",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\car-f-92(3.71).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                     

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {                                      
         Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\car-s-91.stu","2","35","0.13",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\car-s-91(4.39).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                     

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {                                      
        Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\ear-f-83.stu","3","24","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\ear-f-83(32.63).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                     

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {                                      
        Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\hec-s-92","4","18","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\hec-s-92(10.04).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                     

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {                                      
       Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\kfu-s-93.stu","5","20","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\kfu-s-93(12.90).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                     

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {                                      
        Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\lse-f-91.stu","6","18","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\lse-f-91(9.82).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                     

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {                                      
       Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\pur-s-93.stu","7","42","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\pur-s-93(4.49).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                     

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {                                      
         Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\rye-s-93.stu","8","23","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\rye-s-93(7.93).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                     

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {                                      
       Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\sta-f-83.stu","9","13","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\sta-f-83(157.03).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                     

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {                                       
         Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\tre-s-92.stu","10","23","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\tre-s-92(7.72).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                      

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {                                       
        Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\uta-s-92.stu","11","35","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\uta-s-92(3.04).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                      

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {                                       
        Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\ute-s-92.stu","12","10","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\ute-s-92(24.77).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                      

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {                                       
       Handler firstProb = new Handler("C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\toronto\\yor-f-83.stu","13","21","0.27",
       "C:\\Users\\Nikos\\Desktop\\ΝΙΚΟΣ\\μεταπτυχιακος\\solutions\\yor-f-83(34.71).sol");
       firstProb.createAnalyzer(new Extractor());
       this.dispose();
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
